### ISSUE TITLE
Special chars in title and content not working

### ISSUE THREAD

**Issue by Binnette** [fossar/selfoss#1002]
Hi, it seems that special char as "œ" are truncated in titles and content. It seems that this char is ""

Exemple with this article: "Faircode, [...] pour leurs **œ**uvres,..."
https://www.developpez.com/actu/176408/Faircode-une-alternative-a-l-Open-Source-qui-voudrait-que-les-createurs-soient-payes-pour-leurs-oeuvres-cela-reste-t-il-de-l-open-source/

Title:
![2017-12-02 18_57_26-selfoss 61](https://user-images.githubusercontent.com/6597721/33518295-cd2a9d08-d792-11e7-8ff3-a297f5012e32.png)

Content:
![2017-12-02 19_08_08-selfoss 61](https://user-images.githubusercontent.com/6597721/33518377-40491bba-d794-11e7-97a2-586cdb129807.png)

Notice that the œ is not present.
Here is the RSS: https://web.developpez.com/index/rss

**Comment by Binnette** [comment]
If I open https://web.developpez.com/index/rss in Firefox, it can not render it...
![2017-12-02 19_12_33-flux developpement web developpez](https://user-images.githubusercontent.com/6597721/33518414-f2e69fd6-d794-11e7-9fb5-75e6b1212c3b.png)

**Comment by Binnette** [comment]
It seems that our special french quote ’ is not rendered in selfoss.
Notice the difference between ’ and '
I think this is unicode U+2019 or U+02BC
> source: https://fr.wikipedia.org/wiki/Apostrophe_(typographie)

Exemple with the first section of this article : https://www.developpez.com/actu/176408/Faircode-une-alternative-a-l-Open-Source-qui-voudrait-que-les-createurs-soient-payes-pour-leurs-oeuvres-cela-reste-t-il-de-l-open-source/

![2017-12-02 19_19_39-selfoss 61](https://user-images.githubusercontent.com/6597721/33518496-22f2e878-d796-11e7-877a-e4c7f81750bb.png)

5 'special quotes' are missing.

**Comment by jtojnar** [comment]
If you zoom in on the  square, you can see 009C, which is the code of œ in [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) encoding. The feed, however, declares UTF-8 encoding and seems to use in the rest of the file. Not much we can do about that.

**Comment by Binnette** [comment]
What a nice tip !!! I never have to the curiosity to zoom this kind of char ! You just learn me a very usefull trick ! Thanks a lot 👍👍👍😜😀

Ok, so I will contact the website support to report this bug. Thanks a lot 😄

Can you tell me if the "special quote" is a selfoss bug ?

**Comment by jtojnar** [comment]
The ones in front of open seem to be [the typewriter apostrophe](https://codepoints.net/U+0027) consistently, which is in ASCII so it should definitely be visible. I will investigate.

**Comment by Binnette** [comment]
Thanks a lot ! I just have submited the encoding bug to developpez.com team. If they answer me, i will write their response down here ☺️

**Comment by jtojnar** [comment]
It looks like the problem occurs with FullTextRss spout. The article body contains 0x92 (typographic apostrophes in Windows-1252) but the site declares [ISO 8859-1](https://en.wikipedia.org/wiki/ISO/IEC_8859-1#Codepage_layout) encoding which does not actually include the character.

To completely mitigate this, the site should declare `windows-1252` in the `meta charset` tag and fix UTF-8 conversion of the feed (I am guessing they are trying to convert from ISO Latin 1 instead of from the actual encoding).

**Comment by Binnette** [comment]
Hi @jtojnar, since this issue is not fixed by developpez.net, i have just post the problem in the forum [here](https://www.developpez.net/forums/d522078-40/club-professionnels-informatique/mode-d-emploi-aide-aux-nouveaux/reportez-problemes-liens-morts-www-developpez-com-site-forum/#post10545327)

Here is my screenshot of selfoss 2.18:
![rss reader](https://user-images.githubusercontent.com/6597721/47255229-ccf60880-d46d-11e8-8b2d-bf7b369d5ca6.png)

I hope they will fix this issue soon.
Have a nice day 🌞
