### ISSUE TITLE
New Install of 2.18 - Can not refresh source: Internal Server Error

### ISSUE THREAD

**Issue by daprofessa19** [fossar/selfoss#1040]
I have checked everything I can think of, but I still can't update any feeds. I don't see any errors in the logs, but the webpage returns "Can not refresh source: Internal Server Error".

Corresponding entry in access.log is
"POST /selfoss/source/1/update HTTP/1.1" 500 -

DEBUG level logging is not giving me any leads to follow.

**Comment by jtojnar** [comment]
Can you also change `DEBUG` to `1` in `common.php`?

**Comment by daprofessa19** [comment]
Sure, done. When running an update, I see the curl response in default.log and it ends in thumbnail generated  and icon generated, but no items.

**Comment by jtojnar** [comment]
So it does not produce Error 500 any more? Could you check the response for the request in your browser network inspector? Setting `DEBUG` to one should produce more than error occurred in the response. Alternately, could you share the source in question?

**Comment by daprofessa19** [comment]
No, I still get an Error 500 from update. I checked in Chrome Inspect and it shows the 500 error, with all.js in the initiator column.

I have gotten the same error with different source types, such as RSS feed or Youtube channel page.

**Comment by jtojnar** [comment]
If you click the row with the error, what does the Response in the opened pane say?

**Comment by daprofessa19** [comment]
"This request has no response data available"

Following the initiator link brings me to this line.

xhr.send(options.hasContent && options.data || null);

**Comment by niol** [comment]
I cannot reproduce. Does refreshing all sources work?

**Comment by daprofessa19** [comment]
No, I'm not able to refresh any sources. I just don't see any errors in the logs, except for this internal server error. I'm not sure if this has to do with my server config, but I am able to run other php scripts.

**Comment by jtojnar** [comment]
Sorry, this fell into the cracks. We have released selfoss 2.19, which features a significant rewrite so hopefully, the issue got fixed. Please reopen if you are still willing and able to reproduce with the latest version.
