### ISSUE TITLE
Hyperlink Directly to Search Results

### ISSUE THREAD

**Issue by daprofessa19** [fossar/selfoss#1071]
Hello,

Is it possible to craft a URL that will open selfoss and load search results automatically?

**Comment by niol** [comment]
No but it would not be that hard to add this functionality.

**Comment by jtojnar** [comment]
https://github.com/fossar/selfoss/commit/405a3ec2cf49e3dc17421b997930c5b1faebd2fc adds support for this via `search` query string parameter (e.g. `http://localhost/selfoss/newest/all?search=ukraine`).
