### ISSUE TITLE
Use image from RSS feed for thumbnail

### ISSUE THREAD

**Issue by Offerel** [fossar/selfoss#1114]
I have imported a OPML file from Inoreader. All is imported fine. Most of the feeds are set as "RSS Feed" type. A few as "RSS Feed (with FullTextRSS)". The text of the articles will be correctly imported. The images contained in these articles still refer to the original URL of the external page and not to the URL of my Selfoss instance. How can you set it so that the images come from your own Selfoss instead of the external page?

I have made a issue for a app at https://github.com/aminecmi/ReaderforSelfoss/issues/288, but it seems that the issue is more in selfoss itself, instead of the app.

**Comment by niol** [comment]
This is the same as #733 . selfoss does not do that (yet?).

**Comment by Offerel** [comment]
At least with 2.18 stable not.

**Comment by jtojnar** [comment]
What is the reason you want the images to load from selfoss server?

We currently do not download images to your selfoss instance, mainly due to the fact that images can be quite big and you could quickly run out of disk space without some clever storage management.

If your concern is mixed content, you can use [camo](https://github.com/atmos/camo) or some compatible proxy (set `camo_domain` and `camo_key` in `config.ini`).

**Comment by jtojnar** [comment]
Selfoss sources can optionally add a thumbnail to a feed item. The app displays the thumbnail when available.

Currently the following spouts add thumbnails:
* YouTube
* Twitter
* Reddit
* RSS Feed Images

We could add something like the following to the [content extractor spout](https://github.com/SSilence/selfoss/blob/master/spouts/rss/fulltextrss.php)

```php
    public function getThumbnail() {
        if ($this->items === null || $this->valid() === false) {
            return '';
        }

        $item = current($this->items);
        $image = \helpers\Image::findFirstImageSource(@$item->get_content());
        if ($image !== null) {
            return $image;
        }

        return '';
    }
```

but I [do not really like](https://github.com/SSilence/selfoss/issues/969#issuecomment-323085061) how thumbnails work at the moment and am not sure if I want to add more of them.

**Comment by sonicnkt** [comment]
Im just in the process of switching over to selfoss and missed thumbails on my mobile devices. 
The current thumbnail solution is not perfect and i would disable it in the webapp, but i really miss them browsing my feeds on my tablet. 

I think the addtion to the context ectractor would be great and i think i have read allready that you can disable thumbnails in the webview using the config file. 
Maybe thumbnail support can be added to normal rss feeds as well if they contain an image?
This could also be an option in the feed configuration?

**Comment by sonicnkt** [comment]
@jtojnar i used your extraction code and added it to the fulltextrss.php, this is still working fine in the latest 2.19 snapshot (selfoss-2.19-5661343.zip) with all my feeds except phoronix again.  Could this be related to  https://github.com/SSilence/selfoss/issues/1185 ?

Here is my graby config for phoronix (http://www.phoronix.com/rss.php):
```
# Template for Phoronix.com
# http://www.phoronix.com/rss.php

prune: no

author: //div[@class="author"]/a[1]

body: //div[@class="content"]

# Strip Benchmark results
strip: //div/object

#Test URLS
test_url: https://www.phoronix.com/scan.php?page=article&item=fedora-32-benchmarks&num=1
```
I know this is no current feature but i can't figure out why this is not working for this one feed. 
After you fixed the issue with the escaped links graby is working great but no thumbnails show up even tho the scraped html includes images.

**Comment by jtojnar** [comment]
Yeah, `findFirstImageSource` helper likely suffers from the same issue as it uses regex for parsing HTML for performance reasons and to make me sad.
