### ISSUE TITLE
Improve spout filters

### ISSUE THREAD

**Issue by jtojnar** [fossar/selfoss#1125]
I initially wanted to add more advanced filters as part of #858 but since it is a feature many people including me want, I decided it does not make sense to wait for such complex feature to implement this.

I was imagining some graphical filter builder but simple text expressions à la GMail would probably be sufficient for majority of people.

Various considerations:

* Allow filtering by item category (https://github.com/SSilence/selfoss/issues/753)
* Allow filtering by author (https://github.com/SSilence/selfoss/issues/1117)
* Allow to use the same expression language in search

We first need to design the expression language, then the implementation would be rather simple.

Things to investigate:

* GMail-like expressions
    * https://support.google.com/mail/answer/7190?hl=en&visit_id=637008586279581028-1205226982&rd=1
    * :heavy_minus_sign: weird syntax
* XPath 1.0
    * :heavy_plus_sign: standard
    * :heavy_minus_sign: needs converting spout data to XML
    * :grey_question: maybe too powerful
    * :grey_question: maybe too slow
* XPath 2.0
    * :grey_question: maybe too powerful
    * :grey_question: maybe too slow
    * :heavy_minus_sign: external library will be needed (e.g. https://packagist.org/packages/lyquidity/xpath2)
* Some custom subset of combination of the two
* What our competition does?

**Comment by aslmx** [comment]
Any news here? :)

**Comment by jtojnar** [comment]
#1423 implemented support for title, content, author and category filters à la GMail. Though it allows only a single filter at the moment.
