### ISSUE TITLE
Mark as Read or Star in list mode with a few lines in user.css...but there is a problem

### ISSUE THREAD

**Issue by lacereation** [fossar/selfoss#1159]
![Screenshot from 2019-12-08 14-00-27](https://user-images.githubusercontent.com/28577360/70397506-b1c6bf00-19c7-11ea-917d-525a700ae736.png)

This is what my Selfoss looks like.  All it took was
```
.entry-toolbar {
    display: inherit;
    padding: 0px;
    padding-bottom: 10px;
    background: inherit;
    border: 0;
    margin-top: -2px;
}
```
in selfoss/user.css.

**_But it doesn't work!_**

Clicking _mark_ or _star_ does nothing.  I have spent hours messing with the the jquery with no success.  I cannot understand why it does not work.  What would it take to make it work?

**Comment by niol** [comment]
Because actions attached to the click event of those buttons are only added when an entry is opened and for a single entry. See the `entriesToolbar()` function.
For this to work, you need to add some js in `selfoss.events.entries()` that calls `entriesToolbar()` for each entry. This may work.

**Comment by lacereation** [comment]
Ok I essentially got it to work!!  

**and it only took 1 line of javascript!**
in selfoss.events.entries.js
right after
            `selfoss.events.entriesToolbar(fullscreen);`
I added
            `selfoss.events.entriesToolbar();`
It is not dialed in yet.  You have to click an entry and go into the full view, then click something on the toolbar.  After you go back to the list view it works.  It probably needs something like this
           ` if (selfoss.isSmartphone() == false) {
            $('.entry.selected').removeClass('selected');
            parent.addClass('selected');
        }`
with a different argument tho.

**Comment by lacereation** [comment]
This is more than hilarious.  This feature has been requested since probably the day after Selfoss was created and it is probably the only rss reader to not have this feature...and it only took few lines of css and 1 line of js (but will probably need a few more).

**Comment by niol** [comment]
This is quite unpleasing visually although I reckon the feature has been lacking. This is why it has not been uncluded.

**Comment by lacereation** [comment]
Selfoss is sooo good looking, especially compared to all those 3 pane RSS readers, it would take much more than that to make it look bad.  And it could be CSS-ed to be less obtrusive.  Smaller unboldened font, or icons only, maybe shunted off to the bottom corner.
I am sure I am not the only user who prefers to use my mouse instead of keyboard shortcuts and on a tablet or phone having to open every item made it a pita.  How many users turned away from Selfoss because of this?  If I did not get this working I would have been off to something else.

**Comment by lacereation** [comment]
And thanks for your hint Niol!  I had tried that before but it wasn't in the right context or something.  You focused me right where I needed to be.

**Comment by lacereation** [comment]
It turns out that only 1 line of JS is necessary to make this work, along with the few lines of CSS.   In the above post it was just in the wrong place.
In selfoss/public/js/selfoss.events.entries.js --at the top of the file
```
selfoss.events.entries = function() {
    $('.entry, .entry-title').unbind('click');
    // add the following line
    selfoss.events.entriesToolbar();
```
I tried to make it work in user.js but failed.  In fact that was what I tried originally and why I had the problem.
It should be pretty easy to add a config setting of "show toolbar in listview" to make it an option.  I will work on it and do a pull request.

**Comment by jtojnar** [comment]
Yes, that should work, and unlike the previous solution, even as you load new items.

But I think, now that we got rid of the duplicated fullscreen article element, we might get away with [delegated event binding](https://api.jquery.com/on/) so that we do not have to bind and unbind the events all the time.

**Comment by lacereation** [comment]
I am working off of 2.18 here. I see there has been a lot of changes. Obviously,  I need to update to the development ver.

**Comment by lacereation** [comment]
I am now working off of the current version.  To show the toolbar in the list view takes a different CSS selector:
`.entry:not(.expanded) .entry-toolbar {`
When I click Star or Mark I get 
`Cannot mark/unmark/ or star/unstar item: error Internal Server Error.`
I removed the CSS and the 1 line of JS(selfoss.events.entriesToolbar();) and I still get the error. There isn't an "all.js" anymore.  I am thinking the JS is cached + compiled + causing the error, I tried deleting a couple of the js files in  /public to no avail.  What is the equivalent of  deleting all.js? Maybe it is some other bug?

**Comment by lacereation** [comment]
btw, I get that error no matter what view, with keyboard shortcuts or mouse.

**Comment by jtojnar** [comment]
On master, the offline support will cache things in service worker cache. <kbd>ctrl</kbd>-<kbd>f5</kbd> will bypass the cache once and you can clean it using your browser developer tools, or by calling `selfoss.nukeLocalData()` in the developer console.

**Comment by lacereation** [comment]
That worked...but there are some issues doing that.  My sources and tags disappeared from #nav, making feed updates and going into settings inoperable.  And the changes since 2.18 somehow negate the functionality of `selfoss.events.entriesToolbar();` setting the toolbar to respond to click events.  More simply said, it doesn't work anymore.  Any insights into that, jtojnar?

**Comment by jtojnar** [comment]
`selfoss.nukeLocalData()` also logs you out so you will need to log-in again.

The following patch

```patch
--- a/assets/js/selfoss-events-entries.js
+++ b/assets/js/selfoss-events-entries.js
@@ -8,6 +8,8 @@ selfoss.events.entries = function() {
 
     $('.entry, .entry-title').unbind('click');
 
+    selfoss.events.entriesToolbar();
+
     // clear the selected entry
     selfoss.ui.entrySelect(null);
 
```

along with this snippet in `user.css` works for me

```css
.entry:not(.expanded) .entry-toolbar {
    display: block;
}
```

Did you run `npm run build` or `npm run dev` to rebuild the assets after changing the files in assets?

Alternately, the following snippet in `user.js` allows to forgo the source modification:

```javascript

const previousEventsEntries = selfoss.events.entries;

selfoss.events.entries = function() {
    console.log('overriding selfoss.events.entries');
    selfoss.events.entriesToolbar();
    previousEventsEntries();
};
```

**Comment by lacereation** [comment]
I still have some problems, I am getting some Internal server errors, but they are a whole different issue.  The problem was that I didn't do npm run build.  I remember reading about that in the md files but up until now I was just writing the code and refreshing in 2.18 and did it again reflexively.  Sorry about that. It now works even better--there was one minor issue that disappeared.

**Comment by lacereation** [comment]
I would be happy to add this as a config item, and do the jquery, then a pull request.  If you want to just go ahead and do it I am fine with that too.  You are the best man for the job :).  Thanks for all the great work you are doing!

**Comment by jtojnar** [comment]
> I still have some problems, I am getting some Internal server errors, but they are a whole different issue.

Please open an issue for them.

> I would be happy to add this as a config item, and do the jquery, then a pull request.

I think it would be fine to apply the change from https://github.com/SSilence/selfoss/issues/1159#issuecomment-565610255 unconditionally. Hopefully, it will not turn into too much of a performance hog. And then only add config for the CSS change. Though I am not sure about the latter – maybe we can let people change it in `user.css` until we have a proper design.

**Comment by lacereation** [comment]
I will first try to fix it myself. If I can't or if it is something that should be known, I will open an issue.

That's a good way to do it.  Simple.   I have been running this for awhile now and I am very sensitive to resource usage on my 8 year old bargain computer.  I have not noticed any extra overhead at all.

**Comment by lacereation** [comment]
For @niol and anyone else who finds this unpleasing visually, the toolbar can be hidden until the mouse hovers over it:
```
.entry:not(.expanded) .entry-toolbar {
    display: block;
    padding: 0px;
    background: inherit;
    border: 0;
    margin-top: -2px;
    opacity: 0.0;
}

.entry:not(.expanded) .entry-toolbar:hover {
    opacity: 1.0;
}
```
For Smartphone/Tablet the toolbar will come up with not exactly a longpress, but something between a tap and a longpress.  I find that just a little too burdensome, so I will make it work on bigger screens only like this:
```
@media screen and (min-width: 641px) {
    .entry:not(.expanded) .entry-toolbar {
         display: block;
         padding: 0px;
         background: inherit;
        border: 0;
        margin-top: -2px;
        opacity: 0.0;
    }
    .entry:not(.expanded) .entry-toolbar:hover {
         opacity: 1.0;
    }
}
```

**Comment by lacereation** [comment]
I added a wiki page on how to do this, so the only thing that would possibly still make it an issue would be  `selfoss.events.entriesToolbar();`   not being in the code yet.

**Comment by jtojnar** [comment]
On master, the toolbar is always active so the CSS just works.
