### ISSUE TITLE
Breaking API changes in the latest snapshots?

### ISSUE THREAD

**Issue by sonicnkt** [fossar/selfoss#1197]
I noticed that marking items as read is not working anymore with the latest nightly builts of selfoss 2.19 and the Android Client Reader for Selfoss. 

Using the webinterface works fine but with the android client nothing happens. 
I checked the logs but there seems to be nothing of interest regarding the issue.

Can anyone confirm this? 
I moved my setup into a docker container a few weeks ago so im not 100% sure this issue is not realted to my setup.

**Comment by jtojnar** [comment]
I do not think there have been any breaking changes related to marking pages recently. I just tested with selfoss 9f41abb & Reader for Selfoss 1720020321 and both marking items as read by swiping and the _read all_ button in the header bar seem to work.


Do you use the latest app version? It is now only available from F-Droid store:

https://github.com/aminecmi/ReaderforSelfoss#readerforselfoss-only-available-from-f-droid

For debugging, you could try to increase `logger_level` to `DEBUG` in your config.

**Comment by sonicnkt** [comment]
Ah sorry it seems to be my setup, i was using the same selfoss built and reader client.

Before i was running selfoss directly on a nginx server but now im running it in a docker container (nginx, php-fpm) behind a nginx proxy and this seems to be the problem.

I just tried to  connect directly to the container with the app without using the proxy and this solves the problem for me so there seems to be an error with my my proxy configuration. 
Then i switched back to using the proxy and checking the logs. I thought maybe the POST Request to mark the items was not forwarded for some reason. 
So i checked both logs and everything seems fine and then i noticed that it works now for some reason  😕 

only issue in the logs was missing mysql libraries but as im not using mysql i think i can ignore those.

Somehow readding the account in the app fixed the issue but could have sworn that i had tried this before.

Anyway sorry for the issue.

**Comment by davidoskky** [comment]
The currently published version of the reader for selfoss app has a problem: you need to mark stuff as read twice to make it work...
This issue has been solved already, but you'll have to wait for the next version to be released to fix this.

**Comment by jtojnar** [comment]
Do you [mean this issue](https://gitea.amine-louveau.fr/Louvorg/ReaderForSelfoss-multiplatform/issues/72)?

**Comment by davidoskky** [comment]
Yes
