### ISSUE TITLE
How do I install "compose" file?

### ISSUE THREAD

**Issue by kittykat125** [fossar/selfoss#1210]
sorry, I'm a COMPLETE noob. So I donwloaded the entire file to my xampp folder. When I try to open any file in the selfoss directory, it tells me I need to install compose and there are no PHP dependencies. This means I need to install either compose.lock or compose.json, right? I use Virtual Studio Code and Powershell. I also have Docker. 

I tried to install both/either file on PowerShell through the "install-package" command, as well as the "install-script" command. I also tried to run both/either file in Virtual Studio Code. One of them did create launch.json... I've tried to run every other file in the root directory. I still get the same error message. 

Can someone guide me?

**Comment by jtojnar** [comment]
I am not sure `composer` is available through PowerShell’s `install-package` command, you might need to visit https://getcomposer.org/download/ and get it from there.

It might be easier to just download the latest development build of selfoss from [downloads](https://github.com/SSilence/selfoss#download). Then you will not need to bother with composer and every dependency will be included.

Of course, if you want to start developing selfoss, you might actually want to work with the git checkout of selfoss and install composer but maybe it would be easier in Windows subsystem for Linux than Powershell.

**Comment by kittykat125** [comment]
Thank you for responding. I figured out how to do it. Playing with the app now!!!

**Comment by jtojnar** [comment]
Feel free to re-open if you have more questions.
