### ISSUE TITLE
I can't install...

### ISSUE THREAD

**Issue by hoopper** [fossar/selfoss#1214]
After putting all the database data in config.ini ... run cliupdate.php and I get the following error: "The option` logger_destination` must be `error_log` or a file path with the prefix` file : `." What am I doing wrong and what do I have to do ...

**Comment by jtojnar** [comment]
Did you change the vallue of `logger_destination` in your `config.ini`?

**Comment by hoopper** [comment]
In the configuration section of the page https://selfoss.aditu.de/ in "Sample config.ini file with a MySQL database connection:" it does not put anything of "logger_destination". It just says:

[globals]
db_type = mysql
db_host = localhost
db_database = selfoss
db_username = secretagent
db_password = life0fD4ng3r
db_port = 3306

That of course I have changed the values with those of my database ...

by the way the folders (to which you have to change the permission) which permission must have the 777 or another ...

**Comment by jtojnar** [comment]
Weird, then it should just fall back to the contents of `defaults.ini`

https://github.com/SSilence/selfoss/blob/664481dba5387f783627faccda1998d8e2085f3e/defaults.ini#L12

and the condition should pass

https://github.com/SSilence/selfoss/blob/664481dba5387f783627faccda1998d8e2085f3e/src/common.php#L183-L192

Did you copy the `defaults.ini` file too? Does it contain the `logger_destination` line?

What version of selfoss do you use?



> by the way the folders (to which you have to change the permission) which permission must have the 777 or another ...

The permissions will depend on the configuration of your web server. If your web server and PHP process is running under the user who owns the files, you only need first 700, if it is a different user but same group, 770 will be sufficient. If it is a completely different user, you will need to make it writeable for others too (777) but then any user on the server will be able to write it.

**Comment by hoopper** [comment]
Yes, the defaults.ini file has the line logger_destination=file:data/logs/default.log

Is it in defaults.ini where you have to put the data from the database and then rename it to config.ini? Do you have to put any more data?

I say it, because I have done it this way and now it does not give me the error that it gave me (the logger_destination ...) now it just says: "an error has occurred".

**Comment by jtojnar** [comment]
You should not modify `defaults.ini`, only add what you need to `config.ini`. Adding anything more than database should not be necessary.

You can enable more detailed error information by changing `0` to `1` in this line:

https://github.com/SSilence/selfoss/blob/664481dba5387f783627faccda1998d8e2085f3e/src/common.php#L28

Alternately, could you add `var_dump($logger_destination);` at the end of this line:

https://github.com/SSilence/selfoss/blob/664481dba5387f783627faccda1998d8e2085f3e/src/common.php#L183

to see why it is complaining about logger destination.

**Comment by hoopper** [comment]
an error has occurred: include(/mnt/web016/d0/14/51731914/htdocs/selfoss/vendor/composer/../../controllers/Index.php): failed to open stream: No such file or directory [selfoss/vendor/bcosca/fatfree-core/base.php:2190] Base->error() [selfoss/vendor/composer/ClassLoader.php:444] Base->{closure}() [selfoss/vendor/composer/ClassLoader.php:444] include() [selfoss/vendor/composer/ClassLoader.php:322] Composer\Autoload\includeFile() [selfoss/vendor/bcosca/fatfree-core/base.php:1588] class_exists() [selfoss/index.php:80] Base->run()

**Comment by jtojnar** [comment]
That is weird. How did you install selfoss? There should be `controllers/Index.php` file in the selfoss directory.

**Comment by hoopper** [comment]
The thing is that I still haven't been able to install, that's what I'm trying ...
I will only tell you that I have uploaded the folder as it comes in the zip (unzipped) to my ftp, I have given the permissions to the folders that it puts in the instructions ... I put the data from the database to config. ini and uploaded it to ftp and run the address shown in the instructions (with my personal domain) ...
From that point you already know ... they give me the different errors that I have made.
It would be interesting that when you upload the files to ftp, when you go to the web address, an install.php will be loaded with the forms to fill in all the data and thus automate the installation ... in the long run it will be less work for you.

ps... i do not have this directory...

**Comment by jtojnar** [comment]
What zip file did you use? The directory should be in there.

**Comment by hoopper** [comment]
including the controllers directory ...
Now it gives a new error ... HTTP 404 (GET /cliupdate.php) [selfoss / vendor / bcosca / fatfree-core / base.php: 1660] Base-> error () [selfoss / index.php: 80] Base -> run ()

**Comment by jtojnar** [comment]
`cliupdate.php` would need to be executed from command line, it cannot be visited by web browser. You would use `https://yoururl.com/update`.

**Comment by hoopper** [comment]
PDOStatement: Unknown column 'lastseen' in 'where clause' [selfoss/vendor/bcosca/fatfree-core/base.php:2190] Base->error() [selfoss/daos/mysql/Items.php:200] DB\SQL->exec() [selfoss/daos/Items.php:57] daos\mysql\Items->cleanup() [selfoss/helpers/ContentLoader.php:408] daos\Items->cleanup() [selfoss/helpers/ContentLoader.php:37] helpers\ContentLoader->cleanup() [selfoss/controllers/Index.php:181] helpers\ContentLoader->update() [selfoss/vendor/bcosca/fatfree-core/base.php:1806] controllers\Index->update() [selfoss/vendor/bcosca/fatfree-core/base.php:1627] Base->call() [selfoss/index.php:80] Base->run()

**Comment by hoopper** [comment]
the install zip is this https://github.com/SSilence/selfoss/releases/download/2.18/selfoss-2.18.zip

**Comment by jtojnar** [comment]
Did you ever have other version of selfoss installed? This is starting too look more and more broken.

**Comment by jtojnar** [comment]
With the `lastseen` error, I would delete the database and let selfoss create it again.

**Comment by hoopper** [comment]
With the new installation, with a new database (and emptied completely)

keeps giving error: PDOStatement: Unknown column 'lastseen' in 'where clause' [selfoss / vendor / bcosca / fatfree-core / base.php: 2190] Base-> error () [selfoss / daos / mysql / Items.php: 200] DB \ SQL-> exec () [selfoss / damage / Items.php: 57] damage \ mysql \ Items-> cleanup () [selfoss / helpers / ContentLoader.php: 408] damage \ Items-> cleanup () [selfoss / helpers / ContentLoader.php: 37] helpers \ ContentLoader-> cleanup () [selfoss / controllers / Index.php: 181] helpers \ ContentLoader-> update () [selfoss / vendor / bcosca / fatfree-core / base .php: 1806] controllers \ Index-> update () [selfoss / vendor / bcosca / fatfree-core / base.php: 1627] Base-> call () [selfoss / index.php: 80] Base-> run ( )

1) If it connects to my database, why does it create the structure ...
2) The permissions of the folders to be changed, are they changed recursively or does it only affect the top folder?
3) Now if all the folders are there and not a single one is missing ...

**Comment by hoopper** [comment]
if I have to run https://yoururl.com/update ... I consider that I am "updating" ... And therefore I have to change /data/icons into /data/favicons

**Comment by jtojnar** [comment]
> if I have to run https://yoururl.com/update ... I consider that I am "updating" ... And therefore I have to change /data/icons into /data/favicons

The update instructions are for updating from older version of selfoss to a newer one, so they are not necessary when updating sources.

> * If it connects to my database, why does it create the structure ...

It creates the structure to spare you the need to create it yourself but for some reason it is buggy in your case.

What happens when you just visit selfoss at `https://yoururl.com`, not the `/update` address, after deleting the database?

> * The permissions of the folders to be changed, are they changed recursively or does it only affect the top folder?

Just those five directories need to be writeable: data/cache, data/favicons, data/logs, data/thumbnails, data/sqlite and public/, no need for recursive.

**Comment by jtojnar** [comment]
Alternately, you can try using the development builds https://github.com/SSilence/selfoss#download, they contain a lot of fixes.

**Comment by hoopper** [comment]
please do not close this thread and I will inform you ...

**Comment by jtojnar** [comment]
Did you manage to do it in the end?

**Comment by hoopper** [comment]
Well, in the end, since I'm a Spanish speaker (and I don't know much about English), and I have a memory like a fish... I didn't even remember the topic... please close the topic. I don't know if I will try the installation again...
