### ISSUE TITLE
Question, not issue

### ISSUE THREAD

**Issue by MatthK** [fossar/selfoss#1224]
After I finally got it to work, I really do start to like Selfoss.

One thing that I noticed is, that some RSS feeds provide more or less a single sentence as content, while others have the full article including HTML coding in it. So I have two questions regarding this.

1, Is there a way to get the content of the full article to have Selfoss follow the link and parse the text there?
2. Is it possible to strip the html code and just store the plain text of the article? Ideally it would "keep" the images in some form in the database, but that's probably too much to ask.

And what is the difference between "RSS Feed" and the other "RSS Feed xxx"? Is the (with FullTextRSS) something like in question 1?

**Comment by jtojnar** [comment]
> 1, Is there a way to get the content of the full article to have Selfoss follow the link and parse the text there?

Yes, that is what _RSS Feed (with FullTextRSS)_ does. It is named _RSS Feed (with content extraction)_ in the development versions, which will hopefully make it clearer.

> 2. Is it possible to strip the html code and just store the plain text of the article?

It is not currently possible but maybe we could implement it? For a feature request, we would need to know:

1. Why do you want to strip HTML code?
2. Do you want it on some feeds or all of them?

Maybe some other questions I am too tired to come up with at the moment.

> Ideally it would "keep" the images in some form in the database, but that's probably too much to ask.

What do you mean? If we stripped HTML, there would be no images, would there?

> And what is the difference between "RSS Feed" and the other "RSS Feed xxx"? Is the (with FullTextRSS) something like in question 1?

* _Images_ are same as regular RSS, only they add a thumbnail (taken either from RSS enclosures or the linked web page when there are no enclosures).
* _Enclosures_ are RSS extension for adding multimedia files to the feed. If there are enclosures, they will be added to the end of the content. Only image enclosures are currently supported.
* _Instapaper_ is supposed to do context extraction using an online service that got shut down. We ought to remove it but will need to add a migration script first.

**Comment by MatthK** [comment]
That's awesome. I wasn't sure at first that it would fetch the full article, as it didn't seem to work when I first checked. But probably I was a little too inpatient.

Is there a way to set Selfoss to use "private" browsing?

South China Morning Post (for example https://www.scmp.com/rss/318421/feed) allows a few articles to be read freely per month before you need to pay. Normally, when browsing in private mode, it works to get beyond that limit. So I'm curious if there is a way to simulate that too?

**Comment by niol** [comment]
I think we do not keep cookies in the selfoss crawler, so it is using private browsing by default.

**Comment by MatthK** [comment]
Hmm, ok. Too bad then.
