### ISSUE TITLE
Homepage: Link to iOS app not working

### ISSUE THREAD

**Issue by HonkXL** [fossar/selfoss#1228]
On the homepage selfoss.aditu.de there is this text:

third party apps for iOS and Android (Selfoss and RSS Reader for Selfoss) available

When I click to "iOS" on iPad or iPhone, I am forwarded to the AppStore App and then I get this message:
"This app is not available in your contry or region". I am using the German App Store.

I know it's a 3rd party app, but I think there should be a information on the homepage, that the app is only available in selected countries.

**Comment by jtojnar** [comment]
Sorry about that, the app does not seem to be available any more for unknown reasons so I have removed the link in https://github.com/fossar/selfoss/commit/1bd6df9ba34ab04ae701a346998f44f6dfd36db0. Unfortunately, I do not have a direct access to the website so the changes are only updated when there is a new release of selfoss.

**Comment by desbest** [comment]
I am planning on making an iphone app for Selfoss some time in the future. But I'll have to learn Cocoa Touch, Obj-C, Swift and React Native first which has a learning curve, so don't hold your breath.

**Comment by davidoskky** [comment]
@aminecmi is also planning to make the Android app Reader for Selfoss working on iPhone, however this will likely take some time.
https://github.com/aminecmi/ReaderforSelfoss/pull/409#issuecomment-1038219924

**Comment by jtojnar** [comment]
The website is now automatically updated from the repo thanks to Netlify: https://selfoss.aditu.de/
