### ISSUE TITLE
Search box on the left panel

### ISSUE THREAD

**Issue by StyXman** [fossar/selfoss#1231]
Currently the search box, first, must be open; and second, only with a button at the top of the article list. Would it be too hard to move it to a permanent text entry in the 'Filter' box on the left panel? That would make it instantly available, except for (I guess) the tablet/phone layouts (I never tried the web interface on those; I use Reader for Selfoss instead).

**Comment by jtojnar** [comment]
It should be fairly simple to make it scroll – just change `position` to `fixed` here:

https://github.com/fossar/selfoss/blob/c87e14aaba42abe281ca3c859a0006fb292ff22c/assets/styles/main.scss#L367

Not sure if there are any downsides.

**Comment by jtojnar** [comment]
Does not seem to cause any issues in brief testing on mobile, tablet or desktop layouts.

**Comment by jtojnar** [comment]
Thanks for reporting. This has been on my mind for a while and your issue finally got me to fix it.

**Comment by StyXman** [comment]
\o/
