### ISSUE TITLE
Error loading feed content: fsockopen error: Connection timed out

### ISSUE THREAD

**Issue by fschwind** [fossar/selfoss#1239]
Nearly all of me feeds started getting a socket-timeout when they are updated (since a few weeks or months?).

"error loading feed content: fsockopen error: Connection timed out"

I'm using "curl --silent -i --insecure https://<host>/Update" to update my feeds, which works for 10 out of ~30 feeds. All the feeds are reachable when I try them "by hand". E.g. "curl -i --insecure http://what-if.xkcd.com/feed.atom" yields a response, but selfoss shows a timeout when updating it.

<img width="1325" alt="xkcd" src="https://user-images.githubusercontent.com/17920899/103478548-cbebf000-4dc7-11eb-9464-23c321808533.png">

The Update.php shows following HTTP-ERROR 500

an error occuredHTTP/1.1 500 Internal Server Error
Date: Sun, 03 Jan 2021 12:20:01 GMT
Server: Apache
Set-Cookie: PHPSESSID=ujbf1junpmtmnshtvju9rj26c8; expires=Tue, 02-Feb-2021 12:20:01 GMT; Max-Age=2592000; path=/; domain=xxx; secure; HttpOnly
X-Powered-By: Fat-Free Framework
X-Frame-Options: SAMEORIGIN
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Cache-Control: max-age=-1
Expires: Sun, 03 Jan 2021 12:31:04 +0000
Last-Modified: Sun, 03 Jan 2021 12:31:05 +0000
Content-Length: 16
Connection: close
Content-Type: text/html; charset=UTF-8

At first I thought about the X-Frame-Option. But since some feeds are still working, it must be something else.

I absolutely have no clue what might have changed. I sieved thru the logs and code but did not find anything suspicious.

380371 [2021-01-03 13:26:39] selfoss.ERROR: error loading feed content for xkcd {"exception":"[object] (Exception(code: 0): fsockopen error: Connection timed out at /home/jester/public_html/selfoss/spouts/rss/feed.php:160)
380372 [stacktrace]
380373 #0 /home/jester/public_html/selfoss/helpers/ContentLoader.php(99): spouts\^Mss\\feed->load(Array)
380374 #1 /home/jester/public_html/selfoss/helpers/ContentLoader.php(35): helpers\\ContentLoader->fetch(Array)
380375 #2 /home/jester/public_html/selfoss/controllers/Index.php(181): helpers\\ContentLoader->update()
380376 #3 /home/jester/public_html/selfoss/vendor/bcosca/fatfree-core/base.php(1806): controllers\\Index->update(Object(Base), Array, 'controllers\\\\Ind...')
380377 #4 /home/jester/public_html/selfoss/vendor/bcosca/fatfree-core/base.php(1627): Base->call(Array, Array, Array)
380378 #5 /home/jester/public_html/selfoss/index.php(80): Base->run()
380379 #6 {main}
380380 "}

 Does anyone have a clue where I might look?

Best 
 Florian

**Comment by jtojnar** [comment]
Maybe PHP update changed the default timeout? Maybe try a [latest development build](https://github.com/fossar/selfoss#download) – the fetcher’s reliability was greatly improved since 2.18.

**Comment by fschwind** [comment]
Any chance I can set the timeout to a different value in Selfoss (although 10 seconds should be enough)?

**Comment by jtojnar** [comment]
Maybe try adding `$this->feed->set_timeout(60);` around here:

https://github.com/fossar/selfoss/blob/2.18/spouts/rss/feed.php#L143

http://simplepie.org/api/class-SimplePie.html#_set_timeout

**Comment by fschwind** [comment]
Thanks for your help, but I finally (after some hours of debugging)  figured out that it had nothing to do with php or changes in selfoss. After the last reboot of my server the iptable rules for ipv6 somehow got mixed up and therefor not all of my feeds could be updated!

None the less I will update to the latest development build in the near future.
