### ISSUE TITLE
Escaped characters in lateral bar

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1241]
In the lateral bar if the name of a tag or a source contains a character that needs to be escaped in html, the escaped version is displayed. & is displayed as &amp; and so on.

To reproduce this issue you can add a source, inserting the character & in the title or in the tag.

**Comment by jtojnar** [comment]
Thanks for reporting. This was a downfall from https://github.com/fossar/selfoss/pull/1184 and it should be fixed now.
