### ISSUE TITLE
entry-next and entry-newwindow does not work in 2.19-SNAPSHOT

### ISSUE THREAD

**Issue by xvasek** [fossar/selfoss#1248]
I use user.css with this content:

`.entry-toolbar .entry-next, .entry-toolbar .entry-newwindow {
    display: block;
}`

Which displays the by-default hidden "next" and "open" buttons in the top toolbar on the phone or when the browser windows is narrow. The problem is, that with current snapshot these buttons do not work - both buttons only close the article and return me to the list.

Is there any possibility to:

1. Make those buttons do their functions
2. Add option to config to show those buttons, so that user.css is not necessary

For the "Open" I can use button at the bottom of article, which is OK, until I have some really long article I want to open. :-) But for "next" I don't have space key on my mobile.

**Comment by jtojnar** [comment]
Thanks for reporting. I have pushed a fix for the open link and a workaround for the next button. I will do a proper fix later.

**Comment by xvasek** [comment]
Thank you very much, your support is best I have ever seen. :-)
