### ISSUE TITLE
All articles in three columns

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1250]
I upgraded to 9af53e9411dc2800bf3f3da50c33ca6876ac0302.
All articles are now displayed in three columns, even the ones too long to fit the screen.

**Comment by jtojnar** [comment]
Do those articles have images by any chance?

**Comment by jtojnar** [comment]
Thanks for reporting. I managed to reproduce it and it should be fixed by https://github.com/fossar/selfoss/commit/7eccbc8cacfd4b5cf9c48ee4a070acbffa0bb993. Please verify and report back if you still have the issue.

**Comment by davidoskky** [comment]
7eccbc8cacfd4b5cf9c48ee4a070acbffa0bb993 does not fix the issue for me.

**Comment by davidoskky** [comment]
Today the problem disappeard, but I have no idea as to why...
Yesterday the problem was there and I did not change anything since then.

**Comment by jtojnar** [comment]
Maybe cache?
