### ISSUE TITLE
Inconsistent api datetime format

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1251]
I am running 7eccbc8cacfd4b5cf9c48ee4a070acbffa0bb993.
The datetime I get from the api is different from the one described in the docs.
Here is one example from one article in my selfoss instance: 
`"datetime":{"date":"2021-03-21 10:32:00.000000","timezone_type":3,"timezone":"Europe\/Berlin"}`

This is nested and different from what described in the docs: `"2013-04-07T13:43:00+01:00"`

**Comment by jtojnar** [comment]
Oops, that was a nasty bug. Thanks for reporting.
