### ISSUE TITLE
Youtube Playlist spout

### ISSUE THREAD

**Issue by toonn** [fossar/selfoss#1254]
I love Selfoss' Youtube Channel spout, it's the only no-nonsense way to follow Youtube creators. The only caveat being the recent "Premiere" feature, it'd be great if Selfoss could add a badge to such videos to indicate they're not watchable yet, should i submit another feature request for this?

Recently I've found myself wanting to follow specific playlists though and this doesn't seem to work when added as "Youtube Channel"s.

Example playlist URL: https://www.youtube.com/playlist?list=PLJtitKU0CAehsdcybehbPFHObmWsKtQcY

**Comment by jtojnar** [comment]
Good idea.

Looks like there is a RSS feed so we could make the YouTube spout handle playlist URLs as well:

https://www.youtube.com/feeds/videos.xml?playlist_id=PLJtitKU0CAehsdcybehbPFHObmWsKtQcY

Not yet sure if we should make it a new spout or just extend the existing YouTube one.

Also thanks for reminding me about the premieres, I have been also bugged by them. Opened https://github.com/fossar/selfoss/issues/1256 to track that feature.
