### ISSUE TITLE
Switch away from fatfree for database

### ISSUE THREAD

**Issue by jtojnar** [fossar/selfoss#1266]
Slowly tearing fatfree out of the codebase.

We should probably wait for after 2.19 so that we can use stuff depending on newer PHP.

Alternatives:

- [dibi](https://dibiphp.com/)
- https://packagist.org/?query=pdo

See also:

- https://github.com/fossar/selfoss/pull/1261
- https://github.com/fossar/selfoss/issues/1084
- https://github.com/fossar/selfoss/issues/1265

**Comment by desbest** [comment]
Out of curiosity, what is wrong with Fat Free Framework? Why don't you recommend it?

**Comment by jtojnar** [comment]
This was done in https://github.com/fossar/selfoss/commit/e71194b10abd6c46dcc287ccec0b367e553d0ab1.
