### ISSUE TITLE
Closing items does not work reliable on iOS in 2.19-fd8f195

### ISSUE THREAD

**Issue by heull001** [fossar/selfoss#1276]
I am blind and using the built-in screenreader Voiceover on iOS. I don't know, if this problem appears without screenreader too.

The button to close items does not work reliable. Sometimes I press it and it works, sometimes I have to click on the headline of the choosen item too and after this it works, sometimes just nothing happens. That's especially bad, because before opening a new item, all other items have to be closed. So for blind people using iOS (in fact, most blind people who use a smartphone are using iOS), this version of selfoss is not usable.

**Comment by jtojnar** [comment]
I cannot reproduce that issue, though I only have access to Android phone. However, there have been quite a few changes in the upcoming 2.19 release (see the [development snapshots](https://github.com/fossar/selfoss#download)), which might have fixed the issue, as well as improve accessibility in general. What version of selfoss do you use?

**Comment by jtojnar** [comment]
Sorry, I just noticed you specified the revision in the title.

I made [some more changes](https://github.com/fossar/selfoss/commit/788d32f5c9d2bd10fcd0229a05dc5807da863830) to how the close button works (though it should mostly affect performance, so unless it was caused by that I do not see how it could fix it).

I will try to borrow an iPhone next week and test selfoss with Voicover there.

**Comment by heull001** [comment]
Yes, I tried 2.19-dc41450. As you supposed, this change had no effect on this problem.

I had a look at the code, but I am not familar enough to react to give any hints, it looks good for me, sorry.

**Comment by jtojnar** [comment]
Just tried this with latest selfoss on an iPhone in Safari with a VoiceOver enabled and still cannot reproduce it. When I double tapped the close button, it always seemed to close (though sometimes I accidentally chose the vertical scrollbar).

I must say that the usability does not feel very good. I would expect the navigation (swiping right) to just select next item in the feed but it seems to jump over each link/text (even selecting the bullet points separating the date from author and source, which it definitely should not do). Is that how you use selfoss? Do you have any suggestion to make the workflow better?

**Comment by heull001** [comment]
I tested again with 2.19-dc41450, same problem. I deactivated voiceover and let my wife click the button, It worked, but she had to scroll out to see it, maybe could be the problem, that Voiceover focuses the button when it is not displayed and it doesn't work in this case?

The usability is no problem, you can turn the voiceover-rotor to headlines and swipe up and down instead of left and right and it jumps to the next headline. In fact, this is one of the reasons why it is so important to use correct html-tags.

**Comment by heull001** [comment]
It works now. I updated to iOS 15 since the last test, so it could have been a problem of Safari.

**Comment by jtojnar** [comment]
Thanks for reporting back. Let’s reopen if it comes back.
