### ISSUE TITLE
The key 'o' doesn't work correctly

### ISSUE THREAD

**Issue by adkurz** [fossar/selfoss#1277]
If I use o to open an article, only the actions are shown. If I use the enter key instead, everything works perfectly (the content is shown).
I'm blind and use NVDA on Windows 10 X64 with Firefox and Chrome.

**Comment by jtojnar** [comment]
Thanks for reporting. This should be fixed by 788d32f5c9d2bd10fcd0229a05dc5807da863830. You can get the latest snapshot as a [development build](https://github.com/fossar/selfoss#download).

**Comment by adkurz** [comment]
Thanks, it's working now.
