### ISSUE TITLE
Api offset not working

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1278]
I am on the latest commit: 2.19-dc41450
The offset parameter for listing items in the api seems to have no effect.
Calling `/items?items=200&offset=200` produces the same result as `/items?items=200`

**Comment by jtojnar** [comment]
Successive parameters need to be separated by `&` not, `?`, see https://en.wikipedia.org/wiki/Query_string.

**Comment by jtojnar** [comment]
Looks like there has been a bug either way. Should be fixed now, thanks for reporting.

**Comment by davidoskky** [comment]
Sorry, my bad... I mistyped
It is now fixed
