### ISSUE TITLE
Can't build selfoss with current parcel version

### ISSUE THREAD

**Issue by dgsiegel** [fossar/selfoss#1279]
I followed the instructions given here: https://github.com/fossar/selfoss#development

When running `npm run build` either in the main directory or inside `assets`, I get the following error:

```
selfoss/assets > npm run build

> @ build /tmp/selfoss/assets
> parcel build index.html opml.html hashpassword.html --dist-dir ../public/ --public-url ./

🚨 Build failed.
Error: ENOENT: no such file or directory, open 'file%3A/tmp/selfoss/assets/node_modules/reset-css/sass/_reset.scss'
Error: ENOENT: no such file or directory, open 'file%3A/tmp/selfoss/assets/node_modules/reset-css/sass/_reset.scss'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `parcel build index.html opml.html hashpassword.html --dist-dir ../public/ --public-url ./`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

`node_modules/reset-css/sass/_reset.scss'` does exist, it just seems to url encode the path which does result in a non-existent path. I've quickly tried newer parcel versions and they don't show this behaviour (but I ran into other issues).

What version of parcel (and parcel plugins) are you using?

**Comment by jtojnar** [comment]
That is weird. Parcel should be pinned by the [lockfile](https://github.com/fossar/selfoss/blob/1a1838ebc264c043913c8c6f8fb7b36a743f5c9c/assets/package-lock.json#L50) to `2.0.0-beta.3.1` (installed by running `npm run install-dependencies`, or `npm install` in the `assets/` directory). What parcel version did you use?

**Comment by dgsiegel** [comment]
Thanks for the hint, I had disabled package-lock on my system. Re-enabling it for this repo resolves this issue.
