### ISSUE TITLE
Clicking active filter/tag/source should reload it

### ISSUE THREAD

**Issue by jtojnar** [fossar/selfoss#1287]
As mentioned in the second point in https://selfoss.aditu.de/forum/index.php?id=1447, in 2.18, clicking the current active filter/tag/source in the navbar triggered a reload of the `EntriesPage`. Since we switched to react-router in https://github.com/fossar/selfoss/commit/405a3ec2cf49e3dc17421b997930c5b1faebd2fc, it no longer works because it is URL-driven and clicking the link does not change the URL.

**Comment by deathbybandaid** [comment]
I just made the switch from 2.18 to 2.19 and this is definitely one of those features I'm missing. However the improvements to the code outweigh this tiny change that I have to reload the page by other means.

**Comment by deathbybandaid** [comment]
Just grabbed 2.19-4fcf02f and this works perfectly!

Thank you so much!
