### ISSUE TITLE
Issues managing sources via /manage/sources

### ISSUE THREAD

**Issue by deathbybandaid** [fossar/selfoss#1302]
When Trying to delete a feed I receive:

![image](https://user-images.githubusercontent.com/18010545/148392551-103e5976-97d4-432e-8fcc-d8dd38d3aaca.png)

However, when I use curl via cli, I can delete as a workaround.

`curl -X "DELETE" "http://localhost/source/374?username=XXXXXXXXXXX&password=XXXXXXXXXXX"`

Additionally, sometime between `2.19-9407240` and `2.19-59b73ff` I receive the following when trying to add new sources:

![image](https://user-images.githubusercontent.com/18010545/148393401-c5226eb4-b06d-4573-aaa3-11e094e8b4eb.png)

**Comment by jtojnar** [comment]
Sorry about that, I broke some routes in https://github.com/fossar/selfoss/commit/befb1c49f2785fc02a19fcb897071f7fe316bb70 but it should be fixed by https://github.com/fossar/selfoss/commit/525e186bb0ac833db77927a74d0fe32df4321ef6.

**Comment by jtojnar** [comment]
Turns out the fix was incomplete. Should be fixed now.

**Comment by deathbybandaid** [comment]
Tested, and deletion and adding are indeed fixed!

Thanks!
