### ISSUE TITLE
Manage/sources display source IDs

### ISSUE THREAD

**Issue by deathbybandaid** [fossar/selfoss#1306]
Excuse the bad job via snipping tool, but should get the concept across. It would be useful if the manage sources page had the source-ID number listed somehow.

![image](https://user-images.githubusercontent.com/18010545/148953180-b387832c-ee15-464f-83fc-922831261149.png)

Doing so would allow me to more easily write a python script service to update certain feeds at specific intervals via the api instead of updating all at once.

**Comment by jtojnar** [comment]
I do not want to display that in the interface but we could expose it in a data attribute again and then user could make it visible using custom CSS.

**Comment by jtojnar** [comment]
The following should work with https://github.com/fossar/selfoss/commit/4a9ef4e196ed3d1fdd4633920d3a82bb1c6b84a7:

```css
.source[data-id]::after {
    content: attr(data-id);
}
```

**Comment by deathbybandaid** [comment]
````
.source[data-id]::after {
    content: " • Source-ID: " attr(data-id);
}
````

Looks a bit cleaner

**Comment by jtojnar** [comment]
Closing as something that does not fit in selfoss and can be achieved with user code.
