### ISSUE TITLE
WebUI Body is missing

### ISSUE THREAD

**Issue by OneClickPonyy** [fossar/selfoss#1307]
My WebUI Body is "missing". Its something with Java i guess
i also get this when im looking in to the dev tools:
![image](https://user-images.githubusercontent.com/59981755/149117294-122574e6-94fb-4deb-b331-ea2b971736b6.png)

This is what the page looks like: 
![image](https://user-images.githubusercontent.com/59981755/149117455-5d5a9e3c-c8bc-40d3-afaa-0b561dd7fd1f.png)

*The machine is set up new so i dont have the problem after a update or something

Thanks in advance :)

**Comment by jtojnar** [comment]
Hi. How did you install selfoss? Particularly, what web server (Apache/nginx/…) and OS do you use?

This looks like the assets are not correctly pointed to the `public/` directory. With Apache, this is controlled by `.htaccess` file, which it is not enabled by default.

**Comment by OneClickPonyy** [comment]
> 

Hei, 

the OS im using is centos7 release 7.9.2009
Apache: httpd-2.4.6.97.el7
php: 5.4.16
composer: 2.2.4 
mysql: ver 15.1  mariadb 5.5.68

this is the manual  ive used: https://www.vultr.com/docs/how-to-install-selfoss-rss-reader-on-a-centos-7-lamp-vps
hope this info helps : )

**Comment by jtojnar** [comment]
This part should have taken care of that:

> Open the file:
> 
> ```
> sudo vi /etc/httpd/conf/httpd.conf
> ```
> 
> Then find the section that starts with <Directory "/var/www/html"> and change AllowOverride none to AllowOverride All. The end result (with all comments removed) will look something like this:
> 
> ```
> <Directory "/var/www/html">
>     Options Indexes FollowSymLinks
>     AllowOverride All
>     Require all granted
> </Directory>
> ```
> 
> Now save and close the Apache configuration file.

Assuming you installed selfoss under `/var/www/html`.

And do not forget to restart Apache (using `sudo systemctl restart httpd`).

**Comment by OneClickPonyy** [comment]
> This part should have taken care of that:
> 
> > Open the file:
> > ```
> > sudo vi /etc/httpd/conf/httpd.conf
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then find the section that starts with <Directory "/var/www/html"> and change AllowOverride none to AllowOverride All. The end result (with all comments removed) will look something like this:
> > ```
> > <Directory "/var/www/html">
> >     Options Indexes FollowSymLinks
> >     AllowOverride All
> >     Require all granted
> > </Directory>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Now save and close the Apache configuration file.
> 
> Assuming you installed selfoss under `/var/www/html`.
> 
> And do not forget to restart Apache (using `sudo systemctl restart httpd`).


The file was already configurated like this
![image](https://user-images.githubusercontent.com/59981755/149167452-29bdeac2-d4ca-4fa2-b662-d93a48c8c760.png)

and the files from selfoss are in the right directory
![image](https://user-images.githubusercontent.com/59981755/149167584-2e92fe6c-b6f6-4cde-affc-fc099c6cfe63.png)

**Comment by jtojnar** [comment]
Then that looks alright. Could you also check the contents of the `public/` directory and what URL do you get when you click on the link in the browser developer tools?
Either the files are missing or selfoss is somehow incorrectly detecting a base path and producing wrong URLs.

**Comment by OneClickPonyy** [comment]
> Then that looks alright. Could you also check the contents of the `public/` directory and what URL do you get when you click on the link in the browser developer tools? Either the files are missing or selfoss is somehow incorrectly detecting a base path and producing wrong URLs.

so in public it looks like this:
![image](https://user-images.githubusercontent.com/59981755/149316929-4d8f52a8-3773-42e8-a3cc-a216912a388d.png)

and wehen i click on the dev URL it comes to this site:
https://www.chromium.org/developers/design-documents/create-amazing-password-forms

**Comment by jtojnar** [comment]
Sorry, I meant the links on the right in the failed requests (like `all.js`). Alternately, you can check the network panel.

**Comment by OneClickPonyy** [comment]
nothing is happening its just empty field when i click on it - on all links on the right side from the error :(

**Comment by jtojnar** [comment]
Sorry, I misremembered how the dev tools work in Chromium. You need to right click it and then click “Open in new tab”. Then you should be able to see the URL in the address bar. At least I hope so, my console is somewhat different when I tried to simulate this by deleting some file:

![Chromium console showing a HTTP 404 error](https://user-images.githubusercontent.com/705123/149821123-a99c2f63-6bf8-4141-9c35-d0ebed63bc70.png)

**Comment by OneClickPonyy** [comment]
> Sorry, I misremembered how the dev tools work in Chromium. You need to right click it and then click “Open in new tab”. Then you should be able to see the URL in the address bar. At least I hope so, my console is somewhat different when I tried to simulate this by deleting some file:
> 
> ![Chromium console showing a HTTP 404 error](https://user-images.githubusercontent.com/705123/149821123-a99c2f63-6bf8-4141-9c35-d0ebed63bc70.png)

okay so in every link i opened in a new tab i get error 404 every time. 
![image](https://user-images.githubusercontent.com/59981755/149938551-daf40ff4-ded3-4096-827e-b395ded34159.png)
so the files exist that means some path are set false as you said

**Comment by jtojnar** [comment]
From that error, it looks like the files are being found relative to document root (`/`), which should be correctly resolved to the `public/` directory using the following rule:

https://github.com/fossar/selfoss/blob/2.18/.htaccess#L25

So it looks like the issue is in Apache configuration but I exhausted my Apache knowledge and the few [troubleshooting guides I found](https://www.keycdn.com/support/htaccess-not-working) do not provide anything much interesting either.

**Comment by jtojnar** [comment]
I guess you could try putting some gibberish to the top of the `.htaccess` file. That should cause an Error 500 if the file is loaded by Apache.

**Comment by jtojnar** [comment]
selfoss 2.19 has been released, which completely revamps the asset loading. Please open a new issue if you still have problems.
