### ISSUE TITLE
Author name double escaped

### ISSUE THREAD

**Issue by davidoskky** [fossar/selfoss#1317]
The HTML of the author name fetched is not correctly sanified.

For example, fetching with the youtube spout this channel: QualityAndTechnology
`The author name displayed in Selfoss is "Chemometrics &amp; Machine Learning in Copenhagen" instead of "Chemometrics & Machine Learning in Copenhagen"`

**Comment by jtojnar** [comment]
Thanks for reporting. I have fixed it for newly fetched items. For the old one, you can run the SQL command mentioned in the commit message.

Unfortunately, this is not the only problematic item. Courtesy of Simplepie, almost every value returned by the library (except for URIs) has HTML special characters escaped, if it is a plain text and will require a larger revamp (I started on it in https://github.com/fossar/selfoss/pull/1368 but we do not want it to delay 2.19).
