### ISSUE TITLE
Internal Server Error: Fatal error: Module 'imagick' already loaded 

### ISSUE THREAD

**Issue by desbest** [fossar/selfoss#1320]
This is what I see when a load the page.

> Internal Server Error  
> Fatal error: Module 'imagick' already loaded 

Then when I refresh the page it disappears with the page finally loading. But then the error appears again once I refresh the page again.

I'm using Selfoss 2.18

**Comment by jtojnar** [comment]
That sounds like issue with your server config. What operating system (Linux distribution) do you use? On most Linux distros extensions are enabled in separate ini files so you should not have `extension=imagick.so` in `php.ini`.

**Comment by desbest** [comment]
Sorry for the late reply. My laptop was faulty for 2 weeks.
It's using [Cloud Linux](http://cloudlinux.com) which is based on CentOS.
It's using Image Magick 3.4.4
See the attached screenshot.

**Comment by jtojnar** [comment]
Could you check the `php.ini` file contents?

**Comment by desbest** [comment]
The php.ini file does not exist anywhere on my website in the file-folder structure either in the home directory or any subfolders (eg. selfoss/)
However the web host I'm using does virtually generate a php.ini file with some settings filled in by default as a preset, for security reasons.
![multi php ini editor cpanel for desbest portfolio](https://user-images.githubusercontent.com/1139316/155883144-4b083412-c0f5-407f-86ac-3c540805f40a.png)

**Comment by jtojnar** [comment]
There must be a php.ini somewhere on the system (e.g. /etc/php.ini 
according to 
https://www.rootusers.com/where-is-the-php-ini-configuration-file-in-centos/). 
You can also try to look at the “editor mode” on the web page.

**Comment by desbest** [comment]
I've looked at the editor mode and the text box is blank. 
By the way, that MultiPHP INI Editor feature in Cpanel, it automatically detects every php.ini file stored on my website.

I don't have root access to the server as I'm using a reseller account, not a vps. If you're looking for something specific in advance, can you let me know what that is?

![Screenshot 2022-02-27 at 13-47-39 cPanel - MultiPHP INI Editor](https://user-images.githubusercontent.com/1139316/155885026-020d8a5a-da8b-46ab-845c-bec0a53c7ec8.png)

**Comment by jtojnar** [comment]
The error sounds like you have `extension=imagick.so` line in both `/etc/php.ini` and `/etc/php.d/imagick.ini`. So without a root access, you might need to contact your host.

Alternately, you might want to try the [nightly build of selfoss](https://github.com/fossar/selfoss#download) – it [handles improperly configured web server more gracefully](https://github.com/fossar/selfoss/commit/6993cfbd7c271b2f68302599e59949318836e967).

**Comment by desbest** [comment]
It looks like you've provided the wrong hyperlink on your readme.
Why does the "download latest" link go to the nightly build of 3 months ago, while the "nightly list" link goes to the full listing with the latest being 3 days ago?

**Comment by jtojnar** [comment]
It looks like Cloudsmith is buggy again. I will have to contact support.

**Comment by desbest** [comment]
Look at this cloudsmith bug.
![cloudsmith bug with selfoss nightly versions packages](https://user-images.githubusercontent.com/1139316/155888698-e3833d2f-cf61-48aa-bb94-97f69d486b47.png)

**Comment by desbest** [comment]
I've just tried it in Selfoss 2.19 nightly and it works with no error.

**Comment by jtojnar** [comment]
Yeah, it contains a change that [ignores the error](https://github.com/fossar/selfoss/issues/1192) but that does not mean the error is not still there. It is better to have your host fix the `php.ini` settings since it can potentially cause issues to other apps as well.
