### ISSUE TITLE
load list error: error internal server error

### ISSUE THREAD

**Issue by Vis-Wing** [fossar/selfoss#1325]
2022/03/24 09:51:40 [error] 1847#1847: *20 FastCGI sent in stderr: "PHP message: PDOStatement: Tablespace '`selfoss`.`sources`' exists.

**Comment by jtojnar** [comment]
Hi, what version of selfoss and database server do you use?

**Comment by Vis-Wing** [comment]
v2.18 and mysql 5.7.37

**Comment by Vis-Wing** [comment]
/selfoss/data/logs/default.log  => [2022-03-24 10:00:26] selfoss.ERROR: PDOStatement: Tablespace '`selfoss`.`sources`' exists.

**Comment by jtojnar** [comment]
That is weird. It should not try to create the table when it exists:

https://github.com/fossar/selfoss/blob/2.18/daos/mysql/Database.php#L90-L92

Could you try to enable debug by changing `0` in this line to `1`:

https://github.com/fossar/selfoss/blob/2.18/common.php#L16

**Comment by Vis-Wing** [comment]
I change https://github.com/fossar/selfoss/blob/2.18/common.php#L16 to 1  . Then what should I do?

**Comment by Vis-Wing** [comment]
Can I delete the 'sources' ?

**Comment by jtojnar** [comment]
> I change [`2.18`/common.php#L16](https://github.com/fossar/selfoss/blob/2.18/common.php?rgh-link-date=2022-03-24T10%3A15%3A00Z#L16) to 1 . Then what should I do?

Try it again to see if the error message contains more details.

> Can I delete the 'sources' ?

You can try to delete the database or tables if you do not have anything important data there.

**Comment by Vis-Wing** [comment]
Details of the error are as follows:

2022/03/24 10:18:42 [error] 44478#44478: *11 FastCGI sent in stderr: "PHP message: PDOStatement: Tablespace '`selfoss`.`sources`' exists.
PHP message: [vendor/bcosca/fatfree-core/base.php:2190] Base->error()
PHP message: [daos/mysql/Database.php:92] DB\SQL->exec()
PHP message: [daos/Tags.php:23] daos\mysql\Database->__construct()
PHP message: [controllers/Index.php:48] daos\Tags->__construct()
PHP message: [vendor/bcosca/fatfree-core/base.php:1806] controllers\Index->home()
PHP message: [vendor/bcosca/fatfree-core/base.php:1627] Base->call()
PHP message: [index.php:80] Base->run()" while reading response header from upstream, client: 192.168.17.1, server: 192.168.17.169, request: "GET /?offset=0&itemsPerPage=50&search=&type=unread&tag=&source=&sourcesNav=false&ajax=true HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "192.168.17.169"

**Comment by Vis-Wing** [comment]
where is the 'sources'? 
How should I delete the 'sources'?

**Comment by jtojnar** [comment]
It should be in the MySQL database you set in `config.ini`.

**Comment by Vis-Wing** [comment]
Sorry, I can't solve this problem for the time being. I reset the image and expect others to solve this problem.

**Comment by jtojnar** [comment]
Sorry to hear that. What image do you mean?

**Comment by Vis-Wing** [comment]
Sorry, It is Virtual Machine Image  /(ㄒoㄒ)/~~

**Comment by jtojnar** [comment]
Is that some kind of pre-prepared selfoss virtual machine? I do not think we have one of those.

**Comment by Vis-Wing** [comment]
That is a Linux virtual machine. I took a snapshot to prevent errors

**Comment by jtojnar** [comment]
Looking at the [MySQL docs](https://dev.mysql.com/doc/refman/8.0/en/innodb-file-per-table-tablespaces.html), apparently InnoDB engine creates a tablespace for each database table by default. So the error you are seeing was likely caused by some MySQL failure that created the tablespace but not the table. That is pretty weird, it is first time I am seeing such issue, and Google does not show many hits either.

Maybe you could try executing `` DROP TABLESPACE `selfoss`.`sources` `` in the MySQL database to try to remove the tablespace. But it still sounds like something is wrong with the database itself for it to have produced such error.

**Comment by Vis-Wing** [comment]
After I delete tablespace, the program works normally. Thank you very much.
