### ISSUE TITLE
Error after installation through YunoHost

### ISSUE THREAD

**Issue by Binnette** [fossar/selfoss#1327]
Hi @jtojnar, I just wanted to let you know (and the community) that there is a "Work In Pprogress" by @ericgaspar about integrating selfoss in the platform [YunoHost](https://yunohost.org/). @ericgaspar and I are experiencing some JSON Parse error after installation is complete.

- The JSON Parse error we are currently experiencing: https://github.com/YunoHost-Apps/selfoss_ynh/commit/2cb317b33a88b47cc764626fa43c46a1a465a8da

![image](https://user-images.githubusercontent.com/6597721/160358073-0a3f5d16-5d06-4b0f-8c75-2a8b8bc58121.png)

- The WIP project: https://github.com/YunoHost-Apps/selfoss_ynh
- An issue related to YunoHost (not selfoss) when installing selfoss through it: https://github.com/YunoHost-Apps/selfoss_ynh/issues/2

Have a nice day.

**Comment by jtojnar** [comment]
For the `JSON.parse` error, you can look at the requests in the Network panel of your Browser’s developer tools. You can see what the HTTP response contains.

**Comment by jtojnar** [comment]
When it’s ready, we can add a link to readme.

**Comment by farvardin** [comment]
@jtojnar I've installed selfoss on yunohost, and got this "Load list error: parsererror SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data" error as well. I've looked into the developper tools in the network panel, the response is only the html code for the page, with nothing related to json or json code. What else could I investigate?

![image](https://user-images.githubusercontent.com/477243/161300073-c430110b-6215-48bb-bf75-b4a86ea67e0a.png)

![image](https://user-images.githubusercontent.com/477243/161300335-c199002b-998a-41b3-8a1b-7aa8aea39f75.png)

**Comment by jtojnar** [comment]
That is weird.

It should not show the HTML, when `ajax` is passed in the query string for the `GET` request:

https://github.com/fossar/selfoss/blob/2.18/controllers/Index.php#L35

Which should be the case:

https://github.com/fossar/selfoss/blob/2.18/public/js/selfoss-db.js#L107
https://github.com/fossar/selfoss/blob/2.18/public/js/selfoss-base.js#L25

**Comment by Binnette** [comment]
Selfoss is now working nicely on Yunohost 🎉
https://github.com/YunoHost-Apps/selfoss_ynh
