### ISSUE TITLE
PHP 8.1: issue with boolean values (unread, starred)

### ISSUE THREAD

**Issue by flozz** [fossar/selfoss#1330]
Hello,

I have an issue when running Selfoss with PHP 8.1: all articles are displayed as read (but are not) and the counter on the left menu has the right count of unread articles. This issue is reproductible only with PHP 8.1, everything works as intended with PHP 8.0.

----

Here is the item in the **database**:

![image](https://user-images.githubusercontent.com/971438/162445623-910c1fa3-7d18-41ce-b951-3f383a071724.png)

Here is what the browser receive with **PHP 8.1**:

![image](https://user-images.githubusercontent.com/971438/162445738-6a3f2206-2bfd-4507-a7fc-7995f97e7653.png)

And here is what the browser receive when running Selfoss with **PHP 8.0**:

![image](https://user-images.githubusercontent.com/971438/162445945-76eed6c6-d8db-46fa-99f2-1e5d3026a3cd.png)

----

I found the following breaking change in the PHP doc that may explain the issue:

>  PDO::ATTR_STRINGIFY_FETCHES now stringifies values of type bool to "0" or "1". Previously bools were not stringified. 

→ https://www.php.net/manual/en/migration81.incompatible.php

I cannot dig more myself but I hope this will help :)

**Comment by jtojnar** [comment]
Could you please clarify which database backend this is?

**Comment by flozz** [comment]
I tried with both sqlite and mysql

**Comment by jtojnar** [comment]
Actually, looks like it happens in both MySQL and SQLite, only PostgreSQL is not affected. Thanks for reporting, should be fixed now.

**Comment by flozz** [comment]
Yes, I confirm, it works perfectly now. Thank you very much! :D
