### ISSUE TITLE
Upgrade to Ubuntu 22.04 LTS breaks Selfoss

### ISSUE THREAD

**Issue by mrichtarsky** [fossar/selfoss#1333]
Hi,

after upgrading my server to Ubuntu 22.04 LTS Selfoss has trouble with read flags of articles.
On load, all articles are grayed out. Clicking on 'Unread', the articles are still shown and remain grayed out. Clicking on 'Mark as read' apparently has no effect.

Ubuntu switched from php8.0 to 8.1, perhaps this broke something?

**Comment by mrichtarsky** [comment]
I tried with the latest release and also with one from about three months old. My original version was probably half a year old. All of them showed the same behavior. Should I try with HEAD?

**Comment by mrichtarsky** [comment]
#1330 looks exactly like it. Not sure how you create releases, the fix was merged on Apr 8, latest release I tried is from a few hours ago so I suppose it contains it? Anyway I will try again.

**Comment by jtojnar** [comment]
We release the snapshots every time the CI succeeds. But cloudsmith sometimes does not update the latest tag for some reason. Could you try the fresh one on https://cloudsmith.io/~fossar/repos/selfoss-git/packages/?
