### ISSUE TITLE
Reading speed wpm sometimes to high

### ISSUE THREAD

**Issue by AngelCrawford** [fossar/selfoss#1373]
I updated right now to the new 2.19 version, and added the new `reading_speed_wpm` to my config file.

On some articles the reading speed wpm is really high, and on other articles it works just fine.
I can't say why some articles this long, could it be the reviews under the post, that will add words to the count? Or the adds on those sides?

![image](https://user-images.githubusercontent.com/16148683/195420430-66b74765-ee0f-4ded-984f-37efcdc4df87.png)
![image](https://user-images.githubusercontent.com/16148683/195421742-b1fed151-3ec9-4715-b02c-9f3300a6359d.png)

*PS: Thanks for the lovely tool! I really ❤️ it!*

**Comment by jtojnar** [comment]
Thanks for reporting. Are you using regular RSS spout or the _Content extraction_ one? In both cases selfoss reports for me that the first article has 1248 words:

![HTTP response containing word count in developer tools](https://user-images.githubusercontent.com/705123/195430751-c07ed057-b760-4631-b4f0-d794a70af12f.png)

I was not able to reproduce with `reading_speed_wpm=200`:

![Reasonable reading time detected](https://user-images.githubusercontent.com/705123/195430351-3a3703d6-ca78-4cfe-b313-da7cef8ec342.png)

**Comment by AngelCrawford** [comment]
You probably  will hate me xD I found the issue. I added a 1 after the `reading_speed_wpm` to activate it, but you need to add the *words per minute you are able to read* so a 200 for instance... it's late where I live >.<
Thanks for checking!

**Comment by jtojnar** [comment]
Heh, I guessed something like that might be the case but discarded the hypothesis when I thought your reading time was greater than the number of words, which would mean `wpm < 1`, which would just be trimmed to `0`, so that could not be happening. But I actually misread the number in your screenshot :woman_facepalming: here too.
