### ISSUE TITLE
Unread counters do not update properly when "All Read" is clicked

### ISSUE THREAD

**Issue by aslmx** [fossar/selfoss#1388]
Selfoss 2.18:
If you click the "Mark all read" button, it would automatically empty the list and the Unread Counter next to each Tag in the list on the left will automatically update

Selfoss 2.19:
All items that are shown are marked read, but do not disappear. The unread-counter in the tag list is not updated.

**Comment by gerundt** [comment]
Have the same problem with my selfoss installation after the update auf 2.19 🙈
