### ISSUE TITLE
I cannot add a website rss 

### ISSUE THREAD

**Issue by teragoodness** [fossar/selfoss#1395]
I am having issues adding the [Dextrava website](https://dextrava.com/) RSS feed on Selfoss. How can I go about it?

**Comment by jtojnar** [comment]
You would click the _Settings_ button (cloud with arrow icon), then _Add source_ button on the top of the page. Select _RSS Feed_ as the _Type_, and then paste the feed URL to the _URL_ feed:

![image](https://user-images.githubusercontent.com/705123/202559952-289b7ac3-ff88-45e4-864d-998ef4b2ff0f.png)

Or are you having some specific issue?

**Comment by desbest** [comment]
You don't need to know what the specific RSS feed URL is, for any specific website in question, as nowadays that is embedded into the metadata (or meta tag) of the web page that you visit.

```
<link rel="alternate" type="application/rss+xml" title="RSS Feed for petefreitag.com" href="/rss/" />

<link rel="alternate" type="application/atom+xml" title="Atom Feed for petefreitag.com" href="/rss/" />
```

For example, the website **Dextrava**, they should have already included such HTML code in their web page output source. If you press `Ctrl + U` while the website is open, you should find code like the above".

**Comment by jtojnar** [comment]
Closing due to lack of response. Please reopen if the issue persists.
