### ISSUE TITLE
[BUG] [2.19] Cannot load module (on browser console )

### ISSUE THREAD

**Issue by mathys-l** [fossar/selfoss#1420]
Hello,
I'm install the lasted stable version (2.19) run compose install, npm i, npm run build and chown folder, setup my apache2 conf (folder is /var/www/selfoss).

When i'm going to subdomain.domain.tld i have error on my browser console:
```error
The loading of the module at "https://subdomain.domain.tld/index.18516a31.js" was blocked due to a prohibited MIME type ("text/html").
```

Can you help me to fix the bug?

**Comment by jtojnar** [comment]
Hi, what do you see if you if you open https://subdomain.domain.tld/index.18516a31.js

Most likely, you need to enable `.htaccess` support in Apache, see the [Requirements](https://selfoss.aditu.de/docs/administration/requirements/) section of the documentation.

**Comment by mathys-l** [comment]
Thanks,
I add 
```        
<Directory /var/www/selfoss>
   AllowOverride All
</Directory>
```
 on my .conf and that work now.
