### ISSUE TITLE
PHP 8.2.5 support?

### ISSUE THREAD

**Issue by jernst** [fossar/selfoss#1436]
Running into a bunch of issues with PHP 8.2.5 related to fatfree-core as far as I can tell.

Could you clearly document with which PHP versions it is supposed to work, and which versions are known broken and unknown? Thank you :-)

**Comment by jtojnar** [comment]
Thanks for reporting. Are you using 2.19 or a development snapshot? The former should work with PHP 7.2.5 through 8.2, the snapshots require 7.4 at minimum. We are running automatic integration tests for basic usage patterns on all the supported minor PHP versions so at least that should work.

I just tried locally latest development snapshot on PHP 8.2.6 and did not notice anything off either.

I am running my personal instance on development snapshot on PHP 8.1 and have not noticed any issues. Just switched to 8.2, in case the issues occur over time.

Could you please provide more details about the issues (e.g. error traces/logs)?

You might need to add the following to your `config.ini`:

```
logger_level=DEBUG
debug=1
```

**Comment by jernst** [comment]
False alarm, my apologies. I mistakenly referenced a previous build, not the final release of 2.19.
