### ISSUE TITLE
Twitter : You currently have access to a subset of Twitter API v2 endpoints [...]

### ISSUE THREAD

**Issue by adriy-be** [fossar/selfoss#1449]
Hi,

Currently, my twitter flux is not updated. I have this error :

```
error loading feed content: You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

Thanks,

**Comment by jtojnar** [comment]
Yes, that is the unfortunate result of certain person buying Twitter, see https://github.com/fossar/selfoss/issues/1229#issuecomment-1413559453. I lost all motivation on working to support such hostile platform.

I recommend using RSS feed from some [public Nitter instance](https://github.com/zedeus/nitter/wiki/Instances) as an alternative.

**Comment by adriy-be** [comment]
> Yes, that is the unfortunate result of certain person buying Twitter, see [#1229 (comment)](https://github.com/fossar/selfoss/issues/1229#issuecomment-1413559453). I lost all motivation on working to support such hostile platform.
> 
> I recommend using RSS feed from some [public Nitter instance](https://github.com/zedeus/nitter/wiki/Instances) as an alternative.

Ok thanks for your answer :)
