### ISSUE TITLE
Add support for dark mode

### ISSUE THREAD

**Issue by janw-me** [fossar/selfoss#1464]
Title says it all.  
90% of the websites that are in my reader support darkmode.  
But every evening I open Selfoss it's a blinding flash before I can get back to the comfy dimness.

I could not find a existing issue, which surprised me a bit.

**Comment by jtojnar** [comment]
Hi, the issue is #1376

**Comment by janw-me** [comment]
Thanks, I was searching for "dark mode", "darkmode".
