### ISSUE TITLE
Add URL/API to add new Feeds

### ISSUE THREAD

**Issue by jan-battenfeld** [fossar/selfoss#254]
If I want to add a new source i have to
 _copy address -> open selfoss -> goto Sources -> add new -> select rss-handler -> paste the link -> type in title or go back and copy again -> fill in tags -> save_

Would be nice to point new feeds to something like `http://your.selfoss.com/?addFeed=%s` which would fill in Name and Url of `%s` into the AddSource Page.

Many Browser/Addons show an customizable _Add Feed_-icon in the titlebar and simply send the feed-url to an api which would reduce the above to
_click rss symbol -> (click abo) -> fill in tags -> save_

Possible enhancements/problems:
- autodetect source (like twitter or tumblr), otherwise default to rss-feed
- on the fly mode: add NEW label and save without further interaction for rss handler without redirect.

**Comment by funwhilelost** [comment]
:+1:

**Comment by funwhilelost** [comment]
Any progress on this one?  I just bumped up to 2.17 and don't see any mention of it yet.

**Comment by jtojnar** [comment]
@niol added client-side URL handling in #869, so it should be easier to implement it now. However, it is not on my to-do list for 2.18, so unless someone sends a pull request it will have to wait.

**Comment by funwhilelost** [comment]
Awesome.  That work looks great on #869.  I'll wait until that drops and then take a look at making a PR based on that.
