### ISSUE TITLE
Date formatting is not localizationable/internationalizationable in translations

### ISSUE THREAD

**Issue by kristiank** [fossar/selfoss#527]
Many languages and countries don't use the same order of month-day-year elements in the date timestamp. The translation file doesn't seem to allow internationalization of the date datastruct, only

```
lang_timestamp=some {0,date} text {0,time} here
```

**Comment by jtojnar** [comment]
We have used `date.toLocaleDateString()` since https://github.com/fossar/selfoss/commit/78f46a84d68de96a4c2d333635f565f805dfbd79.
