### ISSUE TITLE
title attribute misuse in opml

### ISSUE THREAD

**Issue by hferee** [fossar/selfoss#600]
When importing an OPML, the text attribute (which is compulsory) seems to be ignored and title (which is optional and often misused¹) is taken into account.
This means that when importing a valid OPML with tags/groups like this :
<outline text="mytag">
  <outline title="feed1" text="feed1" .../>
  <outline title="feed2" text="feed2" .../>
</outline>

the tag "mytag is not created". 
To be created, it needs a title (but shouldn't²) :
<outline text="mytag" title="mytag">

In particular selfoss fails to import properly kriss feed's opml.
For compatibility, since it seems to be a common mistake, I propose to keep looking at the title attribute for the tag name, but also to the text attribute if title isn't present.

¹ http://www.therssweblog.com/?guid=20051003145153
² AFAIK, I might have misunderstood the specification

**Comment by jtojnar** [comment]
Thanks for reporting, somehow this fell into cracks but now I have finally fixed it.
