### ISSUE TITLE
Open item in a new (background) tab

### ISSUE THREAD

**Issue by AmrEldib** [fossar/selfoss#695]
The 'Open' button/link does open items in a new tab. However, the browser switches over to that new tab. I try to use the middle button on my mouse, or right click > Open in New Tab. But it doesn't work, because 'open' is not a link.
Adding a button/link to open item in a new background tab would really help because I usually scroll through items, open the ones that are interesting, then go read them rather than scroll, read, scroll, read, etc.
Or, instead of adding a new button, switch the 'open' button to a link that can be opened.
An existing workaround is to click on the name of the feed, it's a direct link to the item, but it's way too subtle.

**Comment by bendem** [comment]
As a workaround, you can click the site name and timestamp at the top of the article (next to the tags). That one is a link.

**Comment by PhrozenByte** [comment]
I implemented this more than 1,5 years ago, but @SSilence rejected the pull request. You can still merge it on your own: #452. [My fork](https://github.com/PhrozenByte/selfoss/tree/master) contains some more (imo very helpful) additions for desktop users [which were rejected](https://github.com/SSilence/selfoss/pulls?q=is%3Apr+is%3Aclosed+author%3APhrozenByte), too.

**Comment by AmrEldib** [comment]
Thanks @PhrozenByte I'll give that a try.
thanks for the tip @bendem I made a note of that in my first post, but it's way too subtle to find.

**Comment by bendem** [comment]
it's actually not that hard to find. Timestamps are the usual place to look at when looking for permalinks (facebook, twitter, G+, blogs...)

**Comment by AmrEldib** [comment]
true, except it's not the timestamp but rather the name of the feed source.

**Comment by drasill** [comment]
With firefox, you should set the option in `about:config` named `browser.tabs.loadDivertedInBackground` to `true`.

Then when you press the `v` key in Selfoss, it opens in a new tab, without switching to it.

There's a solution to do it in the other browsers, I suppose.

**Comment by jtojnar** [comment]
It is actually the timestamp now, as clicking the source opens the source (#794)

**Comment by phyesix** [comment]
Hi all, is there any action about this?

**Comment by marcin93** [comment]
Hi, is that request in contradiction to some plans, best practices, anything?
Provided workaround is working but ... really non-intuitive.

**Comment by jtojnar** [comment]
It is on my to do list. I want to make more buttons in the interface links, just did not get around to it yet.

**Comment by jtojnar** [comment]
Fixed by https://github.com/fossar/selfoss/commit/dba6b06d84fccd6ebdddaf0d4b4616d93974583f. Sorry for the delay.
