### ISSUE TITLE
Accessibility issues for screen reader users

### ISSUE THREAD

**Issue by ndarilek** [fossar/selfoss#736]
Not immediately sure about the specifics of this, but I'm a blind screen reader user, and I can't quite figure out how to do anything with Selfoss. I can't find any links to add feeds, change settings, etc.

A quick glance through the source reveals some empty `<div/>` elements. Are you using empty divs containing glyphs instead of `<button/>` or `<a/>` elements? If so, would you be open to using more standard elements? Without these, you lose a bunch of free a11y and keyboard support that it'd be tough to replicate.

**Comment by jtojnar** [comment]
This is on my to-do list. I already added some captions but many are still missing. Ability to control selfoss via keyboard is also far from ideal. I will work on it now and send a pull request later today.

**Comment by ndarilek** [comment]
Excellent, thanks!

**Comment by jtojnar** [comment]
I uploaded some basic accessibility fixes (#737). Could you please test it?

**Comment by ndarilek** [comment]
Works very nicely so far. Thanks!

**Comment by jtojnar** [comment]
Accessibility is still important and we continue to work on improving selfoss in this area. Closing in favour of #1028 since that one has more details.
