### ISSUE TITLE
Allow filtering by item category

### ISSUE THREAD

**Issue by GutHib** [fossar/selfoss#753]
Question - is it possible to retreive only feeds with a certain tag in the rss/xml code? (I hope I am explaining this properly - when you look at the XML code of any given feed, you will see various custom tags that can be used in APIs and the like to retrieve just certain elements of a feed.)

Is it possible to somehow put these as URL paramters? Or can I use the selfoss filter for this? Thanks!

**Comment by jtojnar** [comment]
Unless the web site supports it, adding URL parameters won’t do you any good.

Also I am not exactly sure what do you intend to achieve. Do you want to extract content of a certain element in each `<item>` and display it in selfoss instead of `<description>`? Or do you want to filter the `<item>`s based on the content of said element?

**Comment by GutHib** [comment]
Yes, I would like to filter items based on the existing tags for each item. Most feeds come with meaningful information in these tags (like, let's say, category or storytype) but it seems like virtually all readers like selfoss ignore these tags and only allow filtering by plaintext search (i.e. looking for a keyword in the title or body). I think it's a shame, because this means routinely ignoring a bag or RSS goodies that really shouldn't be that hard to access.

**Comment by jtojnar** [comment]
Yes, current filters (implemented in #606) can’t do much. It would be nice to have some advanced filtering system, similar to ones [WireShark](https://wiki.wireshark.org/DisplayFilters) or [GMail](https://support.google.com/mail/answer/7190?hl=en) have, or even full-fledged [XPath](https://en.wikipedia.org/wiki/XPath).

I am currently taking exams, maybe someone else can send a PR.

**Comment by jtojnar** [comment]
`item` element in RSS can contain [`category`](https://cyber.harvard.edu/rss/rss.html#ltcategorygtSubelementOfLtitemgt) elements. SimplePie provides [`get_categories`](https://github.com/simplepie/simplepie/blob/a93fb64517b7b7a4a13df481a436d06c53b33428/library/SimplePie/Source.php#L152) method.

**Comment by jtojnar** [comment]
#1423 implemented this for SimplePie-based feeds.
