### ISSUE TITLE
Mobile: hard to hit toolbar buttons

### ISSUE THREAD

**Issue by vpil** [fossar/selfoss#798]
In my Lumia Phone it is quite hard to hit toolbar buttons ("mark as unread", "open"...) in article detail, because buttons are too low-height. And since all misclicks make detail page close, it is quite annoying.
So maybe you can tune css in a similar way I did:

```
.entry-smartphone-share button.entry-share,
.entry-smartphone-share button {
    padding: 20px;
}
.entry-toolbar button {
    margin-top: 0px;
    padding: 6px 0 6px 20px;
}
```

**Comment by jtojnar** [comment]
Should be big enough now.
