### ISSUE TITLE
Wrongful Invalid XML document error

### ISSUE THREAD

**Issue by tuur29** [fossar/selfoss#886]
When trying to parse this rss feed: [https://www.nurgo-software.com/company/news?format=feed&type=rss](https://www.nurgo-software.com/company/news?format=feed&type=rss) I get this error: 
error loading feed content: `This XML document is invalid, likely due to invalid characters. XML error: Mismatched tag at line 36, column 14`

Even though the [w3c validator](https://validator.w3.org/check?uri=https%3A%2F%2Fwww.nurgo-software.com%2Fcompany%2Fnews%3Fformat%3Dfeed%26type%3Drss&charset=%28detect+automatically%29&doctype=Inline&group=0) returns a positive result

**Comment by jtojnar** [comment]
The site seems to use some kind of [protection](https://wordpress.org/plugins/ose-firewall/) that shows an error page but returns `200 OK` HTTP status when it blocks you.

**Comment by jtojnar** [comment]
I contacted the company developing the OSE firewall and they promised to fix the status code in the next release.
