### ISSUE TITLE
Web interface not rendering correctly from outside of the local network, nginx.

### ISSUE THREAD

**Issue by klundry** [fossar/selfoss#922]
I cannot ger the selfoss interface to render correctly or be usable when trying to load it over the internet rather than from inside my local network. I'm using nginx and I think it has something to do with mod_rewrite which is the apache setting. I cannot figure out the correct way to configure the nginx setting.

**Comment by jtojnar** [comment]
There are examples of nginx configuration on the wiki: https://github.com/SSilence/selfoss/wiki/nginx-configuration

**Comment by klundry** [comment]
Hmm, what is the correct way to configure the server name for access outside and in? I am using a dyamic dns service to point to my home network.

**Comment by jtojnar** [comment]
Then you would use the hostname provided by the dynamic DNS service (e.g. `mycomputer.dyndnsprovider.net`). Alternately, you can set the `base_url` key in `config.ini` file to something like `https://mycomputer.dyndnsprovider.net/selfoss/`.

https://nginx.org/en/docs/http/server_names.html
https://selfoss.aditu.de/#configuration_params

**Comment by klundry** [comment]
Thank you.  I thought I had tried setting the server name like that but maybe I typoed something.  Either way, it works now outside my network.  Unfortunately, now it doesn't work inside my network.  Any advice on how to get it to work inside and out at the same time?

**Comment by jtojnar** [comment]
It should be possible  to specify multiple hostnames:

```
server_name yourselfossinstance.com localhost;
```

**Comment by klundry** [comment]
When I add both the hostnames I get the same issue.  However, if I create a 2nd identical server{ section with the other hostname it works.
