### ISSUE TITLE
Make "open" button a link

### ISSUE THREAD

**Issue by desaintmartin** [fossar/selfoss#963]
Hello,
I was in the previous versions a big fan of "right-click -> open link in a new tab" workflow for big articles that were interesting to read in dedicated/original page. Now that it is gone, I still would like to do the same with the "open" button of each item. Unfortunately it is now full javascript so there is no longer any notion of <a>.

I may have time later this month to implement it myself, but right now is simply impossible. :)

What do you think? Is that intentional?

**Comment by jtojnar** [comment]
Previously the feed name was used as a link. In #794, it was changed to link to the list of items in the feed. Instead, the time links to the article now, as it is common on many sites and social networks.

**Comment by desaintmartin** [comment]
Oh I see. It makes this change less critical then. Nevertheless it is always good in a navigation point of view. Anyway, thanks for the tip!

**Comment by jtojnar** [comment]
Yes, I agree that the `<span>`s should be changed to `<button>`s or links. It is tracked in #736.

**Comment by tosigus** [comment]
Not sure, but when i open an article in firefox mobile i can't open it in a background tab using the favicon. It works in the list.

**Comment by jtojnar** [comment]
@tosigus I can open it in background on Firefox Mobile, it is just difficult to touch the icon. Try the following fix https://github.com/SSilence/selfoss/pull/992

**Comment by jtojnar** [comment]
This was fixed by https://github.com/fossar/selfoss/commit/dba6b06d84fccd6ebdddaf0d4b4616d93974583f.
